@startuml
'https://plantuml.com/class-diagram

entity User {
  - username: String
  - alias: String
  - passwordHash: String
}

entity Rating {
  - author: User
  - mediaEntry: MediaEntry
  - stars: int
  - text: String
  - likes: Set<User>
  - timestamp: LocalDateTime
  - hidden: boolean
}

entity MediaEntry {
  - author: User
  - title: String
  - description: String
  - type: MediaType
  - genres: Set<Genre>
  - releaseYear: int
  - minimumAge: int
  - favourites: Set<User>
}

entity Genre {
  - name: String
}

enum MediaType {
  GAME,
  MOVIE,
  SHOW
}

User "1  "<-left-"0..*   " MediaEntry
User "1  "<--"0..*   " Rating
Rating "0..*  "*-left-"1   " MediaEntry
MediaEntry .left. MediaType
MediaEntry "1..*  "*-down-"0..*   " Genre
@enduml